### ISSUE TITLE
Can't find "rlib"

### ISSUE THREAD

**Issue by senioi** [recolic/udp_forwarder_ng#2]
Can you fix this? 
hope cmake suport bsd, like:freebsd,open wrt
thanks

**Comment by recolic** [comment]
https://github.com/recolic/rlib

**Comment by recolic** [comment]
this project was already deprecated. refer to github.com/recolic/udp-forwarder-ex please

**Comment by recolic** [comment]
There's currently no plan to support BSD and OpenWRT, because all my services run on a x86_64 home server. (I don't need it)
It would be good if you can help this

**Comment by recolic** [comment]
Cleaning up old issues...
